### ISSUE TITLE
Integration with Cornice

### ISSUE THREAD

**Issue by pansen** [ergo/pyramid_apispec#9] opened 2018-10-10 18:59 UTC
Hi @ergo , 

thank you very much for that lib. I integrated it nicely working into a playground project, rendered it with a different yaml lib 
```python
    # this requires `apispec==1.0.0b3`
    spec = APISpec(title="Some API", version="1.0.0", openapi_version='3.0.0', plugins=[MarshmallowPlugin()])
    # you can further mutate the spec dict to include things like security definitions
    my_spec = spec.to_dict()
    return Response(pyaml.dump(my_spec, safe=False, force_embed=False, vspacing=[2, 1], string_val_style='"'))
```

convert that output via [`widdershins`](https://github.com/Mermade/widdershins)
```bash
widdershins \
				--headings 4 \
				--resolve true \
				--search false \
				--language_tabs \
					'shell:Bash' \
					'javascript:JavaScript' \
					'python:Python' \
					'ruby:Ruby' \
					'java:Java' \
				--outfile var/index.html.md \
				--verbose \
				--expandBody true \
				var/openapi_direct.yaml
```

and put that `index.html.md` into [Slate](https://github.com/Mermade/widdershins). Much wow ;) 

Now I integrated it into my real project, which is using [Cornice](https://github.com/Cornices/cornice). Unfortunately this does not seem as an easy pick. 

```python
# Cornice `service.name` becomes `route_name` of Pyramid
c1_login_service = Service(name='c1_login',
                           path='/auth',
                           description='Validate a JWT and create a session for us.')

@c1_login_service.post(accept='application/json',
                       schema=PostJwtSchema,
                       validators=(body_validator,),
                       require_csrf=False)
def checkout_authentication(request):
    """
    Validate a JWT and create a session for us

    ---
    x-extension: value
    post:
      # headline/name of the resource (renders as `h2`)
      ...
```

I can register that route, but the docblock is not being read. 

Do you have any guess, or hint where to go?

Cheers

**Comment by ergo** [comment] 2018-10-10 19:35
Interestingly - I also wrote cornice marshmallow support :), I did not look at cornice.ext.apispec - they have that package that currently supports colander schemes.
I don't know why the docblock is not being read, you would have to do some debugging on your end, probably introspection does not pick cornice services or its wrapped somehow.

**Comment by pansen** [comment] 2018-10-10 19:50
The problem seems to be, that in `pyramid_apispec.helpers.add_pyramid_paths` it detects 3 `introspectables` (in the playground, without Cornice, only 1). That alone seems not to be the problem, but that the last of the 3 does not have the `__doc__` anymore.. 

![image](https://user-images.githubusercontent.com/219162/46762056-60914180-ccd6-11e8-8fc8-d91bd5464f20.png)

Ideas?

**Comment by pansen** [comment] 2018-10-10 19:59
Ah. There must be some exclusion on `maybe_view.get("callable").__name__ == ''_fallback_view''`...

**Comment by ergo** [comment] 2018-10-10 20:01
That's probably caused by cornice internals and venusian handling that.
I don't really have time to look at that right now, but it would be easier for us to test if you could provide a minimal test case, it would be useful to file a bug against pyramid_apispec or cornice depending on where the problem appears.
I could look at it when I have a moment, debugging from screenshots will be hard.

**Comment by pansen** [comment] 2018-10-11 13:57
Looking forward for your feedback @ergo

**Comment by ergo** [comment] 2018-10-13 17:31
@pansen Hey, I've left some comments for you.

**Comment by ergo** [comment] 2018-11-07 23:46
@pansen hey any news on this?

**Comment by ergo** [comment] 2019-01-31 20:39
This issue was fixed by other commits.

**Closed** 2019-01-31 20:39 UTC
